### ISSUE TITLE
example about criteria parameter of schema(SchemaEnum[, criteria, schemaID]) function

### ISSUE THREAD

**Issue by trantuan94** [nuintun/node-adodb#102]
I'm trying to get list tables of Access file with schema() function with first parameter is 20 same as your example. But I want to use the second parameter "criteria" of your schema() function. I pass Array Object to it but it throw an error. Please create an example for this problem.

**Comment by nuintun** [comment]
https://docs.microsoft.com/zh-cn/sql/ado/reference/ado-api/schemaenum?view=sql-server-2017
