### ISSUE TITLE
node-adodb engine does not load x64 provider on Windows x64

### ISSUE THREAD

**Issue by SkeletonGamer** [nuintun/node-adodb#106]
Hi,

I added this logs into engine.js file :
<img width="762" alt="capture d ecran 2018-12-19 a 18 13 48" src="https://user-images.githubusercontent.com/779146/50236123-df32eb00-03b9-11e9-9279-4f5940c716b5.png">

In console, on start : 
<img width="294" alt="capture d ecran 2018-12-19 a 18 13 33" src="https://user-images.githubusercontent.com/779146/50236135-e9ed8000-03b9-11e9-8065-4ea2b1ad8321.png">

When I run a request :
<img width="101" alt="capture d ecran 2018-12-19 a 18 07 20" src="https://user-images.githubusercontent.com/779146/50235898-4e5c0f80-03b9-11e9-8732-d70fdc1580de.png">
and throw this error (in French sorry) : 
<img width="475" alt="capture d ecran 2018-12-19 a 18 07 27" src="https://user-images.githubusercontent.com/779146/50235910-56b44a80-03b9-11e9-86b9-68509f8a783e.png">

We clearly see an inconsistency.

Initially, the script detects correctly the 64-bit architecture and the second does not.
So the node-adodb engine wants to loading 32-bit provider on Windows x64.

My workaround pending correction of the bug is to force the use of the cscript64 variable on Windows x64.

**Comment by SkeletonGamer** [comment]
Ok so I analyzed the code and to force the use of x64 cscript.exe, we need to add boolean to open() method : 

`const connection = ADODB.open('Provider=Microsoft.ACE.OLEDB.16.0;Data Source=thedatabase.accdb;Persist Security Info=False;', true);`

For _x64_, use **true**.
For _x86_, use **false**.

By default, the method sends **undefined** and breaks the cscript.exe architecture right choice.

The documentation needs to be updated ! :)

**Comment by mhabib555** [comment]
After trying one complete day, i got your solution.
const connection = ADODB.open('Provider=Microsoft.ACE.OLEDB.12.0;Data Source=thedatabase.accdb;Persist Security Info=False;', true);`

For _x64_, use **true**.
For _x86_, use **false**.

Thanks it worked.

beside this i also had to change (in engine.js)

const cscript32 = path.join(sysroot, archx64 ? 'SysWOW64' : 'System32', 'cscript.exe');
const cscript64 = path.join(sysroot, 'System32/cscript.exe');

to 
const cscript64 = path.join(sysroot, archx64 ? 'SysWOW64' : 'System32', 'cscript.exe');
const cscript32 = path.join(sysroot, 'System32/cscript.exe');

**Comment by nuintun** [comment]
Use `cscript32` by default in 64 system, you can force use `cscript64` set `x64 = true`
