### ISSUE TITLE
unable to fetch date column from ms access db

### ISSUE THREAD

**Issue by mithabavkar** [nuintun/node-adodb#14]
as per subject line enable to capture date column also enable to perform MAX MIN etc. operation in select query.

I am using **"version": "2.0.2"**
my date column (column name - AcctDate and table name - AccountingLog) date format is  - **1/2/1970 3:46:25 PM **
my query is - SELECT MAX(AccountingLog.AcctDate) FROM AccountingLog WHERE AccountingLog.UserId = "'+userID+'"'
i also tried this query aslo -  SELECT * FROM AccountingLog

using above queries enable to capture date column.

Thanks in advance.

**Comment by mithabavkar** [comment]
I got solution from this article.
http://stackoverflow.com/questions/35538522/unable-to-fetch-date-column-from-ms-access-db-node-adodb-node-module-used/35538870#35538870

**Comment by nuintun** [comment]
Please try v2.0.3, I already fixed this bug~
![qq 20160229151140](https://cloud.githubusercontent.com/assets/1730277/13387986/20d7568a-def7-11e5-80f3-f3f090f7762e.png)
