### ISSUE TITLE
Syntax error in INSERT INTO statement

### ISSUE THREAD

**Issue by grayfella** [nuintun/node-adodb#15]
Get a 'Syntax error in INSERT INTO statement' on attempt to insert data into Access database table with an auto increment ID column and specifying which columns to insert.

The insert is successful if no columns are specified and all columns are given a value.

This is Access 2007 compatible file running on Windows 7.

**Comment by nuintun** [comment]
Sorry, can you give an example?

**Comment by omkar-desai** [comment]
@grayfella - One thing you can do is check the names of the columns you wish to insert the data in. Some words are reserved words and you cannot use them in your query. If you want to use them anyway, you can probably enclose them with square brackets like [column].

Hope this helps :smile:
