### ISSUE TITLE
"message": "对象关闭时，不允许操作。"

### ISSUE THREAD

**Issue by farell** [nuintun/node-adodb#17]
下面是我的出错信息：
Exec: query
Params: {
  "connection": "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=DSCDdata.mdb;",
  "sql": "select sensorno as id,data1 as datavalue,unit1 as unit,right(date,10)+
' '+left(time,10) as times from data where date >=#2016-06-00# and time > cdate(
'17:59:55') and sensortype = 'JMZX-212AT'"
}
Error: {
  "valid": false,
  "message": "对象关闭时，不允许操作。"
}

似乎是ADODB.open()未能正确打开，如何知道ADODB.open() 已经正确执行，多谢

**Comment by farell** [comment]
Damn it,
我把日期写成 #2016-06-00#去了，但是为啥返回错误不是“语句错误”而是"对象关闭时，不允许操作。"，还以为是ADODB.open()未能正确打开

**Comment by nuintun** [comment]
我有时间排查下
https://github.com/nuintun/node-adodb/blob/master/lib/adodb.js#L491
这句抓到的错误，然后把链接关闭了~

**Comment by farell** [comment]
多谢
