### ISSUE TITLE
electron 会找不到模块

### ISSUE THREAD

**Issue by wxingheng** [nuintun/node-adodb#226]
![image](https://user-images.githubusercontent.com/20256886/68759641-06864c80-064b-11ea-869a-56c5f10be31a.png)
![image](https://user-images.githubusercontent.com/20256886/68759700-2b7abf80-064b-11ea-9bbf-628ad843253d.png)
![image](https://user-images.githubusercontent.com/20256886/68759702-2cabec80-064b-11ea-90f8-8df8979e626e.png)
![image](https://user-images.githubusercontent.com/20256886/68759775-5238f600-064b-11ea-8f42-f040cd20dc14.png)
![image](https://user-images.githubusercontent.com/20256886/68759803-5f55e500-064b-11ea-9e33-2676e15f73c4.png)

开发环境正常，打包出来的回找不到模块，希望可以提供一下帮助，非常感谢。

**Comment by renant** [comment]
I have the same issue, any update ? Did you solved this @wxingheng ?

**Comment by wxingheng** [comment]
> 我有同样的问题，有更新吗？你解决了这个@wxingheng吗？

I solved it. Good luck

![image](https://user-images.githubusercontent.com/20256886/110621039-be425480-81d4-11eb-8b4b-df4d9ad637a6.png)

wxingheng@outlook.com

**Comment by renant** [comment]
@wxingheng I tried that, but I was unsuccessful.

Are you in the latest version of node-adodb? Did you put this code in electron's main.js?

**Comment by wxingheng** [comment]
> @wxingheng我尝试过，但是没有成功。
> 
> 您是否在使用最新版本的node-adodb？您是否将此代码放入了电子的main.js中？


Tomorrow morning at 09:30 I give you a complete solution, code in the company.

**Comment by wxingheng** [comment]
package.json
![image](https://user-images.githubusercontent.com/20256886/110636908-ceaffa80-81e7-11eb-889f-dc41fab5ba45.png)

![image](https://user-images.githubusercontent.com/20256886/110637314-39613600-81e8-11eb-9558-6858592d9569.png)


main.js

![image](https://user-images.githubusercontent.com/20256886/110637459-601f6c80-81e8-11eb-8a21-6d30eb8ccbf4.png)

**Comment by renant** [comment]
Hi @wxingheng, i used your solution and everything works, thanks!
