### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by siteslave** [nuintun/node-adodb#25]
I'm running node-adodb on electronjs with angular-cli, this is my code

```javascript
   import * as nodeAdodb from 'node-adodb';
    .
    .
    let _p = path.resolve(this.fileImport);
    nodeAdodb.debug = true;
    const connection = nodeAdodb.open(`Provider=Microsoft.Jet.OLEDB.4.0;Data Source=${_p};`);
      connection
        .query('SELECT * FROM M_SUMFUND')
        .on('done', (data: any) => {
          console.log('success');
          console.log(data.records[0]);
        })
        .on('fail', (error: any) => {
          console.log(error);
        });
```

this is error on electron console:

![2017-02-21_121023](https://cloud.githubusercontent.com/assets/526890/23151639/272f7ce0-f82f-11e6-8cfc-0642b70b0b47.png)

**Comment by nuintun** [comment]
Can you help me track this error?

You can add log at [line 36](https://github.com/nuintun/node-adodb/blob/master/lib/proxy.js?ts=2#L36) in ```proxy.js```

I guess it should be caused by ```UTF8 BOM```

**Comment by natanv** [comment]
I'm having a similar problem except that it only occurs when I run my app from the electron builder generated nsis installer

```{ valid: false, message: 'Unexpected token \u0016 in JSON at position 25' }```

**Comment by nuintun** [comment]
Version 3.0.2 is available, please try it.
