### ISSUE TITLE
connection.execute doesn't return RecordsAffected

### ISSUE THREAD

**Issue by newghost** [nuintun/node-adodb#26]
Execute 方法应该返回受影响的行数，根据 MSDN 文档

https://msdn.microsoft.com/en-us/library/windows/desktop/ms675023.aspx

第二个参数为受影响的行数

    Set recordset = connection.Execute (CommandText, RecordsAffected, Options)

不过 jscript 的传入参数都是按值引用的，RecordsAffected无法获取返回结果，可否用VBScript重写adodb.js

让其能返回受影响行业

**Comment by nuintun** [comment]
参考：[@@ROWCOUNT](https://msdn.microsoft.com/zh-cn/library/ms187316.aspx)
