### ISSUE TITLE
Is it possible to run node-adodb inside of a Docker container

### ISSUE THREAD

**Issue by TheKeithStewart** [nuintun/node-adodb#28]
I am going to be running a the process that is utilizing `node-adodb` to connect to an Access database on a Windows Server box.  I am considering using Docker to containerize the Node process.  Docker containers run inside of a Linux VM.  

Is it possible to use this package inside of a Linux VM or is it dependent on drivers that are provided by the Windows operating system?

**Comment by nuintun** [comment]
Sorry, it dependent on drivers that are provided by the Windows operating system :disappointed:
