### ISSUE TITLE
Using node-adodb to run a mdb query with query parameters

### ISSUE THREAD

**Issue by charlie662** [nuintun/node-adodb#29]
Hi,
Thanks for making this project available. I am using it in Node to access a MS Access mdb. Currently I cannot see any way of running queries stored in the mdb which have parameters set.
Example:
```
qUser=
PARAMETERS TEST Long;
SELECT * FROM USERS WHERE ID=[TEST];
```
In node, if i use `connection.query('SELECT * FROM qUser')`, then it will return Error{"valid": false,"message":"Operation is not allowed when the object is closed"}
Is there a way to set the parameter from node?
Thanks
Charles

**Comment by nuintun** [comment]
Sorry，when ```query``` executed complete, it will close the database, so can't store queries!

**Comment by charlie662** [comment]
No problem. Just being able to access an mdb from node is great; parameters would have just been 'the icing on the cake'.
Many thanks
