### ISSUE TITLE
Metadata: No information about the fields within a recordset

### ISSUE THREAD

**Issue by Antony74** [nuintun/node-adodb#31]
I don't think it's possible to get information about the fields within a recordset.  e.g. [Type](https://docs.microsoft.com/en-us/sql/ado/reference/ado-api/type-property-ado) and [DefinedSize](<https://docs.microsoft.com/en-us/sql/ado/reference/ado-api/definedsize-property>).  In regular ADO I would be examining the Recordset's [Fields](https://docs.microsoft.com/en-us/sql/ado/reference/ado-api/fields-collection-ado) collection, but I can see that approach isn't available with node-adodb.

I'm not saying I want to be able to write code that's completely data-driven, but it's nice for a program to be able to look that the fields so this information doesn't have to be duplicated and hard-coded, and so it can be tolerant of small changes to the database.  The problem is particularly acute if a recordset is empty, because then you don't even get a list of fields.

The other thing I've tried to solve this problem myself is accessing the MSysObjects table.  I think this is a bad approach, and the problem I encountered is nothing to do with node-adodb, but for the sake of completeness: Let's edit your example query.js file, just to change the table name and put in some error handling:

```
'use strict';

// External lib
var ADODB = require('../');

// Variable declaration
var connection = ADODB.open('Provider=Microsoft.Jet.OLEDB.4.0;Data Source=node-adodb.mdb;');

process.env.DEBUG = 'ADODB';

connection
  .query('SELECT * FROM MSysObjects')
  .on('done', function(data) {
    console.log('result:', JSON.stringify(data, null, 2));
  })
  .on('fail', function(msg) {
    console.log(msg);
  });
```

<img width="390" alt="node-adodb" src="https://cloud.githubusercontent.com/assets/1577335/26527987/eb4d8f50-4397-11e7-82d2-f8c668b93e4e.png">

**Comment by nuintun** [comment]
:thumbsup: I will add this feature to the next version.

**Comment by nuintun** [comment]
@Antony74 You can try [v3.1.0](https://github.com/nuintun/node-adodb/releases/tag/3.1.0?ts=2)

**Comment by Antony74** [comment]
Thanks, I appreciate the effort that you've put into this.  At the same time I'm concerned that you're duplicating identical field metadata in every record in the recordset.  I fear the overhead this would put on to a live system with thousands of records would be too great.

**Comment by nuintun** [comment]
@Antony74 Try master branch~

**Comment by Antony74** [comment]
That's great, thanks!  I look forward to migrating my software to using node-adodb soon :-)
