### ISSUE TITLE
query a 'Date/Time' column is not working

### ISSUE THREAD

**Issue by Anton2012** [Nuintun/node-adodb#4]
Hi,

if my table includes a date/time column type then this column is not displayed at the query results. What can I do? (using a Microsoft Access Database - .mdb)

Thanks

Toni

**Comment by robcampo** [comment]
See:

https://github.com/Nuintun/node-adodb/issues/3

**Comment by Anton2012** [comment]
Thanks it works, but json result is a string value not a date value.

**Comment by robcampo** [comment]
Right. You could convert it to a date. Understand that's extra effort but should work.

**Comment by Nuintun** [comment]
Thanks, I will fixed in next version.

**Comment by Nuintun** [comment]
Please try https://github.com/Nuintun/node-adodb/releases/tag/1.2.0
