### ISSUE TITLE
Wildcard in node-adodb query returns blank results, but runs OK in MS Access 

### ISSUE THREAD

**Issue by EarthmanWeb** [nuintun/node-adodb#41]
Everything is working fine for normal SELECT queries, and for SELECT queries with a static WHERE clause (eg: ...WHERE Customer id=1 " works fine! )

HOWEVER, When I use a wildcard * in my WHERE clause as above, I receive an empty dataset:
`[]`
 ...Even though the exact same query runs perfectly in MS Access GUI

EG: `DB_QUERY("SELECT * FROM Customers WHERE ContactFirstName LIKE '*Howard*' ", req, res, next);`  returns: `[]` when running in code, but, the SQL statement run in MS Access returns many records:
[Screenshot](https://www.dropbox.com/s/2qro2yz3kv7jx45/Screenshot%202017-10-23%2013.47.03.png?dl=0)

Here is my code:
```
//example of wildcard query

'use strict';
module.exports = (req, res, next) => {
    return DB_QUERY("SELECT * FROM Customers WHERE ContactFirstName LIKE '*Howard*' ", req, res, next);
};

//index.js file


const adodb = require('node-adodb');
const restify = require('restify');
require('restify').plugins;

server.use(restify.plugins.queryParser({ mapParams: true }));
server.use(restify.plugins.bodyParser({ mapParams: true }));
server.use(restify.plugins.acceptParser(server.acceptable));

var DB_PATH = 'C:\\data\\data.mdb';
var ADODB = adodb.open('Provider=Microsoft.Jet.OLEDB.4.0;Data Source=' + DB_PATH);
var DB_QUERY = function(dbQuery, req, res, next, pics){
    var isWin = /^win/.test(process.platform);
    if(!isWin){
      res.send('This should be run on a Windows Machine only to connect to Access DB File at: ' + DB_PATH);
    } else {
        try {
            if (fs.existsSync(DB_PATH)) {
            ADODB.query(dbQuery, true)
            .on('done', function(data) {
                console.log(dbQuery.cyan);
                // console.log('data',data); // why is this empty when i run a wildcard search query???
                res.send(data);
            })
            .on('fail', function(error) {
                console.log('Failed');
                console.log(error);
                res.send(error);
            });
            } else {
            console.log('Failed: file does not exist at:' + this.DB_PATH);
            res.send('Database could not connect - Please contact admin');
            }
        }
        catch (error) {
            console.log('error:'.error);
            res.send(error);
        } finally {
            console.log('Complete');
        }
    }
}
```

Please advise, thanks, am I doing this wrong?

**Comment by EarthmanWeb** [comment]
I was able to solve this by replacing the single quotes with double ones, and replacing the asterisk wildcard symbol used in MS Access with the % sign, instead.

This article pointed me to the solution:

https://social.msdn.microsoft.com/Forums/en-US/5d176ff7-1493-4f11-b322-afb1f0be0063/trouble-getting-sql-query-to-work-using-like-clause-with-astersik-as-wildcard-in-adonet?forum=sqlexpress

**Comment by Thakur62** [comment]
Hi @EarthmanWeb 
I am trying to execute below query of ms access database using node.js . I am passing the id from get operation . It does not filter the result with the ID rather returning the whole data. 

connection
        .query('SELECT * FROM Employee where ID = [id]', id)
