### ISSUE TITLE
Error "Provider cannot be found. It may not be properly installed" on Node 16

### ISSUE THREAD

**Issue by SkeletonGamer** [nuintun/node-adodb#445]
Hi, node-adodb not working on Node 16. 

An error "Provider cannot be found. It may not be properly installed" occurred.

I have uninstalled Node 16.2.0 and reinstalled Node 15.14.0 and everything run.

**Comment by javiquero** [comment]
Hi! Check that your node x86 or x64 installation corresponds to your windows version.
You can see what version of node you are running with this:
console.log (process.arch);

**Comment by SkeletonGamer** [comment]
> Hi! Check that your node x86 or x64 installation corresponds to your windows version.
> You can see what version of node you are running with this:
> console.log (process.arch);

Hello @javiquero ! Effectively, I have downloaded the x86 version of Node 16... Sorry, I am certainly tired !
