### ISSUE TITLE
Binary data retrieval from mdb file?

### ISSUE THREAD

**Issue by EarthmanWeb** [nuintun/node-adodb#45]
Thank you for an excellent plugin, I have it currently powering my node/express api and it is very efficient for my SELECT queries, which is as far as I have gotten with it.

My problem:  I have .jpg image data binary encoded in a relational .mdb database - I would like to use nodeADODB to retrieve the binary data using a select query (or similar), so I can use node to then import the binary data and [display it at an image endpoint in my api](https://stackoverflow.com/a/30218377/3499528) or [write it to a local image file](https://gist.github.com/madhums/e749dca107e26d72b64d)

It is beyond my knowledge how to do this with your plugin's ADO connection, but would be a huge help if you can please provide me with a place to start.

EG:
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/retrieving-binary-data

**Comment by nuintun** [comment]
Binary is already supported in the development version, but not perfect.

**Comment by nuintun** [comment]
@EarthmanWeb EarthmanWeb [4.0.4](https://github.com/nuintun/node-adodb/releases/tag/4.0.4) Already published.

**Comment by EarthmanWeb** [comment]
Thank you - I did not realize that. Can you please point me to the Function
call i would use, if there is no documentation for that functionality yet

**Comment by nuintun** [comment]
Database add a field ```UserAvatar``` and set data type: ```OLE Object```

Execute:
```js
'use strict';

// External lib
const fs = require('fs');
const ADODB = require('node-adodb');

const avatar = fs.readFileSync('./avatar.jpg').toString('hex');

// Variable declaration
const connection = ADODB.open('Provider=Microsoft.Jet.OLEDB.4.0;Data Source=node-adodb.mdb;');

// Execute
connection
  .execute(
    `INSERT INTO Users(UserName, UserSex, UserBirthday, UserMarried, UserAvatar) VALUES ("Binary", "Male", "2017/11/22", 0, "${
      avatar
    }")`
  )
  .then(data => {
    console.log(JSON.stringify(data, null, 2));
  })
  .catch(error => {
    console.log(error);
  });
```

Query:
```js
'use strict';

// External lib
const http = require('http');
const ADODB = require('node-adodb');
// Variable declaration
const connection = ADODB.open('Provider=Microsoft.Jet.OLEDB.4.0;Data Source=node-adodb.mdb;');

http
  .createServer((req, res) => {
    // Query
    connection
      .query('SELECT UserAvatar FROM Users where UserID=6')
      .then(data => {
        res.writeHead(200, { 'content-type': 'image/jpeg' });
        res.end(Buffer.from(data[0].UserAvatar, 'hex'), 'binary');
      })
      .catch(error => {
        res.writeHead(500, { 'content-type': 'text/plain' });
        res.end(error.stack);
      });
  })
  .listen(80);
```

**Comment by EarthmanWeb** [comment]
Thank you for this solution, @nuintun - apologies for my delay on reply, just resuming this project now...

I have tried your suggestion, but when I add the binary field ('UserAvatar'), the query throws this error:

```
internal/buffer.js:30
  throw err;
  ^

Error: Unable to transcode Buffer [U_INVALID_CHAR_FOUND]
    at transcode (internal/buffer.js:27:15)
    at ChildProcess.child.on.exitCode (C:\~Projects\PT1\node_modules\node-adodb\lib\spawn.js:124:22)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[nodemon] app crashed - waiting for file changes before starting...

```
Do you have any suggestions, please?
