### ISSUE TITLE
Execute only one query at time

### ISSUE THREAD

**Issue by Mark-81** [nuintun/node-adodb#46]
I have a Node.js application that add records to an Access 97 database (that I cannot change). Sometimes I get multiple identical records, but I'm trying to avoid this:

`
var DB = require('node-adodb'), dbConnection = DB.open('Provider=Microsoft.Jet.OLEDB.4.0;Data Source=' + settings.database.path + settings.database.db);

// Add only if there isn't an identical record
query = 'INSERT INTO ' + table + '(' + fields + ') ';
query += ' SELECT TOP 1 ' + values;
query += ' FROM ' + table;
query += ' WHERE NOT EXISTS ( SELECT 1 FROM ' + table + ' WHERE ';

 array.forEach(function(element)
 {
     query += "([" + element.name + "]=" + element.value + ") AND ";
 });
 query = query.substr(0, query.length - 4);
 query += ' );';

 dbConnection
     .execute(query)
     .on('done', function (data) {
          return callback({id: id, success: true});
     })
     .on('fail', function (data) {
          console.log(data);
          return callback({id: id, success: false});
      });      
`

I'm afraid if the client makes several requests in a while, each one won't find the record, and all will be add.

How should I avoid this?

**Comment by nuintun** [comment]
Add flag if not exists but executing.

**Comment by Mark-81** [comment]
Would you mind to explain a bit more your hint?

If I understand correctly you're suggesting to set a flag before the execute function to be resetted on the success callback.

I might try it, but the flag it's not enough - I guess. I have to store also the client the request comes from and the actual data.

**Comment by nuintun** [comment]
Like java synchronized.
Only one client can operation database at the same time.
