### ISSUE TITLE
It works perfectly on runtime node but not in PKG

### ISSUE THREAD

**Issue by davidguiodo** [nuintun/node-adodb#49]
Hi and thanks for your great Job !

i just use the adodb provider : Microsoft.ACE.OLEDB.12.0 with the schema function of the ado connection.

it's ok when i use it with node.

Our project needs to use PKG to deliver an executable file.
And every thing is ok, no error, but nothing happens with the schema function : no error, no result

Have you and idea ? Thanks.

David

my code :

var adodb = require('node-adodb');
  const connection = adodb.open('Provider=' + provider + ';Data Source=' + file + ';User ID=admin;Persist Security Info=False;');
  
  var adSchemaTables = 20 // TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
  var adSchemaConstraintColumnUsage = 6
  var schema

  try {
    schema = await connection.schema(adSchemaTables); // HERE NOTHING WITH PKG OK WITH NODE
  } catch(err) {
    logger.error(err)
  }

**Comment by davidguiodo** [comment]
Hi, this my proposition, just change the adodb affectation in proxy.js :

// For PKG, the adodb.js must be included as a resource at the exec root path (for cscript.exe)
const adodb = (__dirname.includes(path.sep + 'snapshot') ? path.join(process.cwd(), 'adodb.js') : path.join(__dirname, 'adodb.js'));

**Comment by nuintun** [comment]
Thanks, I'll fix these problems when I'm free #36 #47.

**Comment by tEiras** [comment]
I allI got the same problem when trying toi use adodb with pkg i got : "Error: Spawn C:\Windows\SysWOW64\cscript.exe error" . For pkg, I put some data in my package.json like this : 
"pkg": {
    "assets": [
      "config-cert.json",
      "cert/key_nopassphrase.key",
      "cert/cert.loopsoftware.fr.crt",
      "node_modules/node-adodb/*"
    ]
  }.

Any help please ?
