### ISSUE TITLE
character encoding

### ISSUE THREAD

**Issue by fratsen** [Nuintun/node-adodb#5]
in process.js, the encoding table is set to 'gbk' - which is for traditional Chinese.

the iconv-lite plugin on which node-adodb relies supports many other character sets (Like 'iso-8859-15' which my access DB uses)

It would be great if the encoding wasn't hard-coded but could be given as (optional) parameter when initializing the plugin.

**Comment by fratsen** [comment]
this can be realized with full backward compatibility with only a few changes, I would appreciate if this makes it into the next build:

1. add the following line to config.js:       **exports.encoding = 'gbk';**
2. replace the 2 occurances in process.js of:      **'gbk'**       by:      **exports.encoding**

then anyone can set the encoding table they need.

For me this would mean one extra line of code being:         **ADODB.encoding = 'iso-8859-15';**

**Comment by Nuintun** [comment]
Thanks, I will add 'encoding' setting in next version.

**Comment by Nuintun** [comment]
Please try https://github.com/Nuintun/node-adodb/releases/tag/1.2.0

**Comment by fratsen** [comment]
Super! I tested it and it works just as expected!

**Comment by Nuintun** [comment]
Thanks
