### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by Falym** [nuintun/node-adodb#50]
Hi Nuitun and thanks for this great job,

I develop an node webkit JS application with MS Access. It worked very well, no problem. But recently, I have an error message that I don't understand :

const ADODB = require('node-adodb');
const connection = ADODB.open('Provider=Microsoft.Jet.OLEDB.4.0;Data Source=D:\\Test\\data.mdb;Jet OLEDB:Database Password=password');

connection
	 .query("select * from t_users where login='"+login.replace(/'/g,"''")+"' and password = '"+pwd.replace(/'/g,"''")+"'")
	  .then(data => {
		  if (data!=undefined && data.length!=0) session = data[0];
	  })
	  .catch(error => {
		displayWarning(error);
	  });

error : 牅敲牵䌠捓楲瑰›❌捡詣⁳₅楗摮睯⁳捓楲瑰䠠獯⁴獥⁴艤慳瑣癩₂畳⁲散瑴⁥慭档湩⹥䌠湯慴瑣穥瘠瑯敲愠浤湩獩牴瑡略⁲祳瑳涊⁥潰牵瀠畬⁳❤湩潦浲瑡潩獮മ.

Do you know what it could be please?

**Comment by Falym** [comment]
I've just check connection without password with database MS Access no password but same result.

Thanks.

**Comment by nuintun** [comment]
This error message returned by `Microsoft.Jet.OLEDB.4.0`, But the output was breaked.

Exec this code with `cscript``` and see output.
```js
var connection = new ActiveXObject('ADODB.Connection');
var recordset = new ActiveXObject('ADODB.Recordset');

// Set CursorLocation
connection.CursorLocation = 3;

// Open
connection.Open('Provider=Microsoft.Jet.OLEDB.4.0;Data Source=D:\Test\data.mdb;Jet OLEDB:Database Password=password');
// Query
recordset.Open("select * from t_users where login='"+login.replace(/'/g,"''")+"' and password = '"+pwd.replace(/'/g,"''")+"'", connection, 0, 1)
```

**Comment by Falym** [comment]
Hi,
Thanks a lot for your reply. The error occurs really about `Microsoft.Jet.OLEDB.4.0`.
cscript return '_**Provider is not registered on the local machine**_'

I followed the instruction in **https://stackoverflow.com/questions/1991643/microsoft-jet-oledb-4-0-provider-is-not-registered-on-the-local-machine** and problem fixed.

Thanks.

**Comment by nuintun** [comment]
@Falym 👍

**Comment by Falym** [comment]
cscript must enalbled :

HKEY_CURRENT_USER\Software\Microsoft\Windows Script Host\Settings\Enabled
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows Script Host\Settings\Enabled

DWORD value to 1
