### ISSUE TITLE
Error on query of .accdb file: database in state that prevents opening

### ISSUE THREAD

**Issue by pellejacobs** [nuintun/node-adodb#51]
When trying to execute a query on an Access 2013, I get the following error: 
`The database has been placed in a state by user 'Admin' on machine 'xxxxx' that prevents it from being opened or locked.`

Here is my code: 
```javascript
const ADODB = require('node-adodb')
const connection = ADODB.open(
  'Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\\Users\\XXXX\\Documents\\database.accdb;Persist Security Info=False;'
)
connection.query('SELECT * FROM Table1').then(console.log).catch(console.error)
````

`*.mdb` files work fine though.

**Comment by pellejacobs** [comment]
After some more trial and error, the connection string `Microsoft.ACE.OLEDB.15.0` actually worked fine, although most resources suggested `Microsoft.ACE.OLEDB.12.0`.

Would you accept a PR that adds an example with these connection strings to the README?

**Comment by nuintun** [comment]
@pellejacobs  Please pull  a PR~ 👍
