### ISSUE TITLE
Provider is not registered on the local machine persist on Windows 10 64bits

### ISSUE THREAD

**Issue by Falym** [nuintun/node-adodb#56]
Hello,

This issue was already discussed on #50 (unknown error) and fixed after installing AccessDatabaseEngine_X64.exe. It's about Provider "Microsoft Jet OLEDB" not register. Now, the problem resurfaces after upgrading Windows 10 automatically and my solution with AccessDatabaseEngine_X64.exe is not working anymore.

Do you have any idea ?
Regards.

**Comment by nuintun** [comment]
Use `AccessDatabaseEngine.exe` 32bit

Now not support 64bit, I will add a config for this

**Comment by Falym** [comment]
Hi nuintun,

Thanks for your reply. The problem is about a Malware Trojan. I've processed clean up my PC and it's OK right now.

Regards,
