### ISSUE TITLE
Return Identity after INSERT INTO request

### ISSUE THREAD

**Issue by SkeletonGamer** [Nuintun/node-adodb#7]
Hello,

I have a problem with an `INSERT INTO` request. I must get the `@@IDENTITY` after add data into my table. But unfortunately, I don't know how to perform this with *node-adodb*. 

In **ASP.NET**, I just made a `SELECT @@IDENTITY`before closing the connection.

Thank you to enlighten me.

**_EDIT:_** I have made some changes in your library. I will fork your project and push my changes.

**Comment by Nuintun** [comment]
3Q, see https://github.com/Nuintun/node-adodb/releases/tag/1.3.0
