### ISSUE TITLE
node-adodb    Error: Spawn C:\Windows\SysWOW64\cscript.exe   

### ISSUE THREAD

**Issue by PedroCieemg** [nuintun/node-adodb#85]
Good afternoon, I'm having this error and I did some procedures to solve it, but I did not get many results, does anyone know how to solve it?

code below

`const ADODB = require('node-adodb');
ADODB.debug = true;

// Connect to the MS Access DB
const connection = ADODB.open('Provider=Microsoft.Jet.OLEDB.4.0; Data Source=\\192.168.0.4\banco_teste\DBCIEE.mdb;'); 
                           // Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\\192.168.0.4\BANCO\DBCIEE.mdb;Persist Security Info=False

 //Query the DB
async function query() {
    try{
        const users = await connection.query('SELECT * FROM CIEE01');

        console.log(JSON.stringify(users, null, 2));
    }catch(error){
        console.error(error);
    }
 }

 query();`

Thank's

**Comment by FelixNose** [comment]
I'm facing the same issue and couldn't solve it yes even after trying various things (I'm using iisnode on windows servers)

**Comment by FelixNose** [comment]
I managed to solve the issue when running it in cmd.exe.
For that I made sure to run the correct access drivers (x64 in my case) and I changed the .execute line from the example to:
`.execute("INSERT INTO Users(UserName, UserSex, UserAge) VALUES ('Newton', 'Male', 25)");`
(exchanged single quotes and double quotes)

Sadly it still doesn't run in iisnode and gives the same error there as it previously did.

**Comment by simonlampen** [comment]
You can get this error if anything in your connection string is incorrect.
eg: it looks like your connection string is not escaped, it should have the backslashes escaped

    wrong    "Provider=Microsoft.Jet.OLEDB.4.0; c:\data\my.mdb;"
    correct  "Provider=Microsoft.Jet.OLEDB.4.0; c:\\data\\my.mdb;"

**Comment by RoelVB** [comment]
Do `console.error(JSON.stringify(error))` instead of `console.error(error)`. This could give you some extra information.

**Comment by rabbitom** [comment]
I got the same error, and it turns out that I spelt the table name wrong in SQL.

**Comment by dallascao** [comment]
It's annoying. Struggling with the issue

It seems the following worked. 
1) Single quote the Data Source.
2) Set 64 bit to false, though my Windows is 64 bit.

ADODB.open(`Provider=Microsoft.ACE.OLEDB.12.0;Data Source='c:\\users\\put files in quotes';`, false)

3) Also be aware that single quotes need to escaped with two single quotes.
const mySql =`UPDATE Pairs SET Target_1036 = 'what the l'fck fckfckfckfck!' WHERE ID = '0000885'`   //give error

const mySql =`UPDATE Pairs SET Target_1036 = 'what the l''fck fckfckfckfck!' WHERE ID = '0000885'`    //works

**Comment by mohamadfg-dev** [comment]
use this code : 
```
    const ADODB = require('node-adodb');
    // ADODB.debug = true;
    const connection = ADODB.open('Provider=Microsoft.ACE.Oledb.12.0;Data Source=C:\\databases\\DB.accdb;', process.arch.includes('64'));
    
    connection.query('SELECT * FROM Table1').then(data => {
        console.log(JSON.stringify(data));
    }).catch(error => {
        console.error(JSON.stringify(error))
    });
```

**Comment by ghost** [comment]
The code above for me does not work, I get:

> TypeError: Cannot read properties of undefined (reading 'includes')

**Comment by RoelVB** [comment]
@Mark-81 that would mean for some reason `process.arch` is undefined.
You could try replacing `process.arch.includes('64')` with `true` (or `false` if you're on 32-bit)

**Comment by idodidodi** [comment]
This solved my issue:
Changing the provider from
Provider=Microsoft.ACE.OLEDB.12.0

To:

Provider=Microsoft.Jet.OLEDB.4.0

**Comment by jant-gg** [comment]
same for me, i was trying to use 32bits while i'm at 64:
const ADODB = require('node-adodb');
ADODB.debug = true;  // Activar depuración si necesitas ver más detalles en las operaciones

// Cambia la ruta a la ubicación de tu archivo de base de datos Access
const connection = ADODB.open('Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\\Users\\Juan\\Documents\\Dbprueba.accdb;', process.arch.includes('64'));

module.exports = connection;
